//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigobMobile.Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SigobMobile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        public static string EnterCredentials {
            get {
                return ResourceManager.GetString("EnterCredentials", resourceCulture);
            }
        }
        
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string SelectApiInstitution {
            get {
                return ResourceManager.GetString("SelectApiInstitution", resourceCulture);
            }
        }
        
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        public static string LoginViewTitle {
            get {
                return ResourceManager.GetString("LoginViewTitle", resourceCulture);
            }
        }
        
        public static string InstitutionsConnect {
            get {
                return ResourceManager.GetString("InstitutionsConnect", resourceCulture);
            }
        }
        
        public static string UserValidationMsg {
            get {
                return ResourceManager.GetString("UserValidationMsg", resourceCulture);
            }
        }
        
        public static string PasswordValidationMsg {
            get {
                return ResourceManager.GetString("PasswordValidationMsg", resourceCulture);
            }
        }
        
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        public static string MasterPageTitle {
            get {
                return ResourceManager.GetString("MasterPageTitle", resourceCulture);
            }
        }
        
        public static string HomeMenu {
            get {
                return ResourceManager.GetString("HomeMenu", resourceCulture);
            }
        }
        
        public static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        public static string TermsAndConditionsMenu {
            get {
                return ResourceManager.GetString("TermsAndConditionsMenu", resourceCulture);
            }
        }
        
        public static string SecurityMenu {
            get {
                return ResourceManager.GetString("SecurityMenu", resourceCulture);
            }
        }
        
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        public static string LogoutMenu {
            get {
                return ResourceManager.GetString("LogoutMenu", resourceCulture);
            }
        }
        
        public static string ApplicationsViewTitle {
            get {
                return ResourceManager.GetString("ApplicationsViewTitle", resourceCulture);
            }
        }
        
        public static string ProfileViewTitle {
            get {
                return ResourceManager.GetString("ProfileViewTitle", resourceCulture);
            }
        }
        
        public static string PersonalDataGroup {
            get {
                return ResourceManager.GetString("PersonalDataGroup", resourceCulture);
            }
        }
        
        public static string OfficialDataGroup {
            get {
                return ResourceManager.GetString("OfficialDataGroup", resourceCulture);
            }
        }
        
        public static string ContactDataGroup {
            get {
                return ResourceManager.GetString("ContactDataGroup", resourceCulture);
            }
        }
        
        public static string FirstNameText {
            get {
                return ResourceManager.GetString("FirstNameText", resourceCulture);
            }
        }
        
        public static string LastNameText {
            get {
                return ResourceManager.GetString("LastNameText", resourceCulture);
            }
        }
        
        public static string InstitutionText {
            get {
                return ResourceManager.GetString("InstitutionText", resourceCulture);
            }
        }
        
        public static string PositionText {
            get {
                return ResourceManager.GetString("PositionText", resourceCulture);
            }
        }
        
        public static string AreaText {
            get {
                return ResourceManager.GetString("AreaText", resourceCulture);
            }
        }
        
        public static string PhoneText {
            get {
                return ResourceManager.GetString("PhoneText", resourceCulture);
            }
        }
        
        public static string CellPhoneText {
            get {
                return ResourceManager.GetString("CellPhoneText", resourceCulture);
            }
        }
        
        public static string EmailText {
            get {
                return ResourceManager.GetString("EmailText", resourceCulture);
            }
        }
        
        public static string UserImageText {
            get {
                return ResourceManager.GetString("UserImageText", resourceCulture);
            }
        }
        
        public static string AgendaViewTitle {
            get {
                return ResourceManager.GetString("AgendaViewTitle", resourceCulture);
            }
        }
        
        public static string InstructionsViewTitle {
            get {
                return ResourceManager.GetString("InstructionsViewTitle", resourceCulture);
            }
        }
        
        public static string TasksViewTitle {
            get {
                return ResourceManager.GetString("TasksViewTitle", resourceCulture);
            }
        }
        
        public static string SearchPlaceHolder {
            get {
                return ResourceManager.GetString("SearchPlaceHolder", resourceCulture);
            }
        }
        
        public static string InManagementStatus {
            get {
                return ResourceManager.GetString("InManagementStatus", resourceCulture);
            }
        }
        
        public static string PendingStatus {
            get {
                return ResourceManager.GetString("PendingStatus", resourceCulture);
            }
        }
        
        public static string CloseToDeadlinedStatus {
            get {
                return ResourceManager.GetString("CloseToDeadlinedStatus", resourceCulture);
            }
        }
        
        public static string ExpiredStatus {
            get {
                return ResourceManager.GetString("ExpiredStatus", resourceCulture);
            }
        }
        
        public static string CompletedStatus {
            get {
                return ResourceManager.GetString("CompletedStatus", resourceCulture);
            }
        }
        
        public static string SuspendedStatus {
            get {
                return ResourceManager.GetString("SuspendedStatus", resourceCulture);
            }
        }
        
        public static string AllStatus {
            get {
                return ResourceManager.GetString("AllStatus", resourceCulture);
            }
        }
        
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
        
        public static string CalendarsTitle {
            get {
                return ResourceManager.GetString("CalendarsTitle", resourceCulture);
            }
        }
        
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        public static string DailyView {
            get {
                return ResourceManager.GetString("DailyView", resourceCulture);
            }
        }
        
        public static string MonthlyView {
            get {
                return ResourceManager.GetString("MonthlyView", resourceCulture);
            }
        }
        
        public static string MultiDayView {
            get {
                return ResourceManager.GetString("MultiDayView", resourceCulture);
            }
        }
        
        public static string AnnualView {
            get {
                return ResourceManager.GetString("AnnualView", resourceCulture);
            }
        }
        
        public static string AgendaListView {
            get {
                return ResourceManager.GetString("AgendaListView", resourceCulture);
            }
        }
        
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        public static string UnselectAll {
            get {
                return ResourceManager.GetString("UnselectAll", resourceCulture);
            }
        }
        
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        public static string HideAll {
            get {
                return ResourceManager.GetString("HideAll", resourceCulture);
            }
        }
        
        public static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        public static string SelectCalendarMessage {
            get {
                return ResourceManager.GetString("SelectCalendarMessage", resourceCulture);
            }
        }
    }
}
